---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
    tier: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-mysql
data:
  database: wordpress
  username: wordpress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
    tier: mysql
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
          - name: MYSQL_DATABASE
            valueForm:
              configMapKeyRef:
                name: wordpress-mysql
                key: database
          - name: MYSWL_USER
            valueForm:  
              configMapKeyRef:
                name: wordpress-mysql
                key: username
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database
                key: root-password
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database
                key: user-password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
---
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
